//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_TransporteSanchez
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHOFERES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHOFERES()
        {
            this.CHOFER_CAMION = new HashSet<CHOFER_CAMION>();
        }
    
        public int Chofer_ID { get; set; }
        public string DNI { get; set; }
        public string CUIL { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoCelular { get; set; }
        public string Email { get; set; }
        public int ProvID { get; set; }
        public int LocID { get; set; }
        public string Calle { get; set; }
        public string AlturaCalle { get; set; }
        public string EstadoChofer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHOFER_CAMION> CHOFER_CAMION { get; set; }
        public virtual LOCALIDADES LOCALIDADES { get; set; }
    }
}
