//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_TransporteSanchez
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTION_CONTENIDO
    {
        public int GestionContenido_ID { get; set; }
        public string Logo { get; set; }
        public string ColorFondo { get; set; }
        public string ColorBotonesMenu { get; set; }
        public string ContenidoPiePagina { get; set; }
        public System.DateTime Fecha_Modi { get; set; }
        public string Usu_Modi { get; set; }
    }
}
