//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_TransporteSanchez
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGTLEntities : DbContext
    {
        public SGTLEntities()
            : base("name=SGTLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAMIONES> CAMIONES { get; set; }
        public virtual DbSet<CHOFER_CAMION> CHOFER_CAMION { get; set; }
        public virtual DbSet<CHOFERES> CHOFERES { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<DESTINO> DESTINO { get; set; }
        public virtual DbSet<LOCALIDADES> LOCALIDADES { get; set; }
        public virtual DbSet<ORIGEN> ORIGEN { get; set; }
        public virtual DbSet<PROFORMAS> PROFORMAS { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<TARIFAS_FIJAS> TARIFAS_FIJAS { get; set; }
        public virtual DbSet<TARIFAS_KM> TARIFAS_KM { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<GRUPOS_USUARIOS> GRUPOS_USUARIOS { get; set; }
        public virtual DbSet<GRUPOS> GRUPOS { get; set; }
        public virtual DbSet<GRUPOS_MENU> GRUPOS_MENU { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<VIAJES> VIAJES { get; set; }
        public virtual DbSet<GESTION_CONTENIDO> GESTION_CONTENIDO { get; set; }
    }
}
