//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_TransporteSanchez
{
    using System;
    using System.Collections.Generic;

    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.GRUPOS_USUARIOS = new HashSet<GRUPOS_USUARIOS>();
        }

        public int Usuario_ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Contraseña { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public string Rol { get; set; }
        public string EstadoUsuario { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPOS_USUARIOS> GRUPOS_USUARIOS { get; set; }
    }
}
